Checkers official
aPusio/projekt-grupowy-javagda49 pull request #44
Opened 2022-01-03 14:43 UTC by Kido-bit

Poprosze o approve :)

2022-01-04 10:35 UTC, aPusio requested changes

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Board.java
> +        boardSpots[0][0] = new Spot(0,0,whiteRegular);
aaaaa zrobiles tutaj cos bardzo niebezpiecznego :D 
pisalem Ci o zrobieniu fabryki. Tu masz przyklad takiego np CarFactory: 
```java
class CarFactory { 
    pubic static Car redSmallCar() { 
        return new Car("red", SIZE.SMALL);
    }
    pubic static Car blueMediumCar() { 
        return new Car("red", SIZE.MEDIUM);
    }
}
```
w Twoim przypadku masz spot i przypisujesz **ta sama instancje** obiektu w rozne pola. 
co za tym idzie jezeli zrobisz cos w stylu spot.getPiece().setRegular(false) to **wszystkie** pionki stana sie damkami :D 
zauwaz ze w fabryce jest zwracany za kazdym razem nowy obietk ale z tymi samymi parametrami

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +        if (player1.isWhite()) {
this jest tu niepotrzebny, jezeli masz tylko jedna zmienna nazwana currentTurnPlayer to kompilator bedzie wiedziec ze to jest pole klasy :) 
BTW mozna szybciej krocej ` currentTurnPlayer = player1.isWhite() ? player1 : player2;`

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +        String startSpotXY = "";
to ze juz zaczynasz tworzyc takie zmienne charStartx, charStarty juz swiadczy o tym ze brakuje Ci plasy Point(x,y) albo Position(x,y), w kazdym badz razie jednej klasy ktora bedzie trzymac x i y jako pola :P

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +        while (true) {
ogolnie funkcje `while (true)` sa bardzo niemilo widziane, zawsze powinienes dac jakis warunek stopu, no ale pewnie nie ma tu calej funkcjonalnosci wiec liczne na to ze w przyszlosci to sie zmieni :)

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +                startX = charStartX - 97;
co to jest 97 i 49 ? to bardzo utrudnia czytelnosc kodu :D

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +        while (true) {
masz 2 prawie takie same fragmenty kodu, to powinna byc funkcja wywolana 2 razy :)

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +        if (this.currentTurnPlayer == players.get(0)) {
tutaj jak wyzej da sie krocej z uzyciem ? i :

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Main.java
> +        int menuOption = Menu.printMenu();
chyba to zla nazwa dla funkcji skoro oprocz printowania zwraca to co odpowiedzial uzytkownik :D

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Menu.java
>      public static int optionInput() {
szkoda ze int a nie enum, bylo by troche czytelniej ale i tak spoko :)

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Main.java
> +            case 1:
lubie to :)

2022-01-04 10:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/RegularPiece.java
> +            if (player.isWhite()) {
wow z tym musiales sie nameczyc :D

2022-01-04 13:05 UTC, Kido-bit commented on src/main/java/com/sda/games/checkers/model/Board.java
> +    public void setBoardSpot(int startX, int startY, int endX, int endY) {
> widze tu tez troche niekonsekwencje :D troche nizej w kodzie sprawdzasz czy tablica nie ma null a potem czy piecie nie jest nullem
> 
> ```java
> if (boardSpots[x][y] == null || boardSpots[x][y].getPiece() == null) {
>                     System.out.print(" ");
> ```
> 
> natomiast w tej linijce poleciales od razu robiac set co moze skutowac nullPointerException :P
> 
> masz 2 opcje wybrniecia z tej sytuacji:
> 
> * dodasz tutaj ifa (malo fajna opcja bo za kazdym razem jak bedziesz chcial operowac na jakims "miejscu" na planszy bedziesz musial sprawdzic czy nie jest nullem
> * troche lepsza opcja zrob funckje ktora ustawi dla wszystkich pol obiekt poczatkowy np initializeBoard. Funkcja ta powinna zwracac board wypelniony Spotami, ewentualnie Piece moglby byc na null :)

chodzi o to ze board ma tylko polowe pol, polowa nigdy nie bedzie uzyta wiec po co ma byc zadeklarowana w tablicy

2022-01-04 13:11 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Board.java
> +    public void setBoardSpot(int startX, int startY, int endX, int endY) {
bo jak zrobisz get i dostaniesz null to nie wiesz czy jest null bo jest poza plansza czy jest null bo jest nie zajeta pionkiem :D

2022-01-04 13:12 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Board.java
> +    public void setBoardSpot(int startX, int startY, int endX, int endY) {
poza tym chyba musisz jakos zainicjalizowac czarne i biale pola na planszy ? bo biale moga sie poruszac tylko po czarnych a czarne po bialych :) ?

2022-01-04 13:35 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Board.java
> +    public void setBoardSpot(int startX, int startY, int endX, int endY) {
przynajmniej tak to sobie wyobrazalem, bedzie jak jeszcze bys zrobil ze get zwraca optionala i ten optional jest poza plansza albo pusty punkt jak jest na palnszy to juz nie musal bys sie przejmowac nullpointerexceptionami :P 
ale jest tez opcja ze nie rozumiem koncepcji tutaj :)

2022-01-05 05:54 UTC, aPusio commented
taka mala sugestia jesli chodzi o opisy commitow: 
- do commitow nie dopisujesz numerow zadan 
- do not mieszaj polski i english to wyglada strange :D 
- zazwyczaj sie przyjmuje ze piszemy w czasie dokonanym, nie musisz byc jakims mistrzem gramatyki wystarczy update zamienic na updated :)

2022-01-05 06:29 UTC, aPusio requested changes
coraz blizej :D

2022-01-05 06:29 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +                    if (board.getBoardSpot(startX, startY) == null || board.getBoardSpot(startX, startY).getPiece() == null) {
fajnie by bylo przeniesc to do boarda w jakiejs funkcji np board.isEmpty() czy cos w tym stylu ;)

2022-01-05 06:29 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +                        if (sourceSpot.isStartSpotValid(board, currentPlayer, startX, startY)) {
a nie lepiej w jednej linijce skoro tak czy siak robisz break ? :) 
```java 
if (sourceSpot.isStartSpotValid(board, currentPlayer, startX, startY) || sourceSpot.hasKill(board, currentPlayer, startX, startY)) {
break;
```

2022-01-05 06:29 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +        board.setSpotsAfterMove(startX, startY, endX, endY);
❤️

2022-01-05 06:29 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Game.java
> +                do {
jest taka fajna zasada ktora zazwyczaj sie sprawdza, jak cos musisz skopiowac to znaczy ze to powinno byc funkcja :) i mysle ze tutaj to pasuje idealnie, zamknij to w jakas funkcje :) 
Ogolnie jesli chodzi o te 2 petle to ze ich nie lubie juz wiesz :D ja bym na poczatek postaral sie znalezc czesci wspolne i powynosil je do funkcji. Funkcje sa spoko, opisuja co robi Twoj kod, a jak kogos interesuje to niech se wejdzie do srodka i sprawdzi jak to sie odbywa

2022-01-05 06:29 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/Spot.java
> +        if (player.isWhite()) {
wow podziwiam ze Ci sie chcialo pisac tyle ifow :D 
jestem prawie pewien ze juz widzisz ze im wiecej ifow tym trudniej cos tu dopisac, i ze dalo by rade to przerobic ale to nie bedzie takie trywialne :P 
BTW w wolnej chwili mozesz looknac :P https://www.youtube.com/watch?v=xAMbxSCSyio

2022-01-07 10:38 UTC, aPusio approved these changes
pewnie znalazl bym pare rzeczy do poprawy ale jest juz w takim stanie ze mysle ze moznemy to spokojnie puscic :D 
BTW potrzeba 2 approvali wiec musisz znalezc kogos jeszcze kto to klepnie zeby zrobic merge :D

2022-01-10 05:49 UTC, aPusio requested changes

2022-01-10 05:49 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/board/Board.java
> +    private static Spot[][] boardSpots = new Spot[BOARD_SIDE_SIZE][BOARD_SIDE_SIZE];
czemu static ?

2022-01-10 05:49 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/board/Spot.java
> +//    public boolean pieceIsWhite(Board board, int x, int y) throws Exception {
jak nie potrzebne to do wywalenia, jak potrzebne do odkomentowania :)

2022-01-10 05:49 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/piece/Piece.java
> +        if (Move.validateExceptionsKilling(board, player, startX, startY)) {
przeciez to `Move.validateLeftSideKilling` zwraca booleana, mozna to napisac bez ifow, z samymi endami i orami (chyba ze uwazacie bedzie to dla was mniej czytelne wtedy zostawcie tak jak jest :) )

2022-01-10 05:49 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/piece/UberPiece.java
> +
???? :P

2022-01-10 05:49 UTC, aPusio commented on src/main/java/com/sda/games/checkers/model/player/Move.java
> +            if (upLeftKill(board, player.isWhite(), startX, startY)) {
no i teraz to wyglada ! :D

2022-01-10 05:51 UTC, aPusio commented
jak pisalem ze mozemy to puscic to mogliscie zrobic merge i otworzyc nowy pull request :) takim sposobem nigdy nic nie wejdzie do mastera :)

2022-01-11 06:41 UTC, aPusio approved these changes
jak dla mnie ostatnie zmiany ok, ale musisz chyba domergowac mastera bo masz konflikty :)

2022-01-11 22:06 UTC, Borowcze approved these changes

2022-01-12 12:00 UTC, aPusio approved these changes

2022-01-12 12:01 UTC, merged